config/routes.rb
Lbdevelopmentv03::Application.routes.draw do

  get "guestlist/add"

  get "guestlist/remove"

  get "billboard/index"

  get "organization_fliers/add"

  get "organization_fliers/delete"

  resources :organizations

  get "realtime/subscription"

  get "realtime/verify"

  get "realtime/change"

  get "error_pages/not_friends"

  get "error_pages/friend_not_found"

  get "error_pages/not_your_flier"

  get "friends/display"

  get "channels/index"

  get "myboard/index"

  get "fliers/index"

  get "fliers/show"

  get "fliers/new"
  post "fliers/edit"

  get "fliers/edit"

  get "fliers/update"

  post "fliers/destroy"

  post "fliers/create"

  get "myfliers/invite"

  post "myfliers/send_invite"
  resources :users
  resources :fliers
  

  get "liveboard/index"

  get "users/create"

  get "users/update"

  get "users/show"

  get "users/destroy"

  get "pages/welcome"

  get "pages/contact"

  get "pages/about"

  get "pages/press"

  post "facebook_update/create"

  match 'login', to: 'auth/facebook'
  match 'logout', to: 'sessions#destroy'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: 'pages#welcome'
  match 'liveboard', to: 'liveboard#index', as: 'liveboard'
  match 'community_select', to: 'users#community_select'
  match 'myboard', to: 'myboard#index'
  match 'liveboard', to: 'liveboard#index'
  match 'myboard_add_flier', to: 'Myfliers#add'
  match 'myboard_delete_flier', to: 'Myfliers#delete'
  match 'contact', to: 'pages#contact'
  match 'help', to: 'pages#help'
  match 'about', to: 'pages#about'
  match 'facebook_update', to: 'facebook_updates#create', as: 'facebookupdates'
  

  match 'sessions_org_create', to: 'sessions#org_create'
  match 'sessions_redirect', to: 'sessions#registration_redirect'
  match 'org_logout', to: 'sessions#org_destroy'
  match 'create_organization', to: 'organizations#register'

  match 'channels/arts', to: "channels#index", :channel_id => "1"
  match 'channels/food', to: "channels#index", :channel_id => "2"
  match 'channels/lecture', to: "channels#index", :channel_id => "3"
  match 'channels/local', to: "channels#index", :channel_id => "4"
  match 'channels/nightlife', to: "channels#index", :channel_id => "5"
  match 'channels/sports', to: "channels#index", :channel_id => "6"

  match 'friends/:id', to: "friends#display"

  match 'not_friends', to: "error_pages#not_friends"
  match 'user_not_found', to: "error_pages#friend_not_found"
  match 'cant_view_flier', to: "error_pages#cant_view_flier"

  match 'create_flier', to: 'fliers#new'
  match 'show_flier', to: 'fliers#show'
  match 'invite', to: 'myfliers#invite'
  match 'edit_flier', to: 'fliers#edit'
  
  match 'org_add_flier', to: 'organization_fliers#add'
  match 'org_delete_flier', to: 'organization_fliers#delete'
  

  root :to => 'pages#welcome'

 
end

app/controllers/liveboard_controller.rb
class LiveboardController < ApplicationController
  def index
    @community_id = current_user.community_id
    @community_name = Community.find_by_id(@community_id).name
    @community = Community.find_by_id(@community_id)
    @channels = Channel.all

    if session[:user_id] #check if this is a user or an organization, if user do the following
    # initiate an array to hold the user's myfliers that will be displayed on liveboard
    

 
    @fliers_for_liveboard = current_user.myfliers.joins(:flier)
  
    #create an array of all fliers that the user has already added
    @current_user_added_fliers = current_user.added_fliers

    #create an array of all fliers that the user created
    @current_user_created_fliers = current_user.created_fliers

    #create an array of fliers that should have an option to add to my board
    @fliers_for_adding = @fliers_for_liveboard - (current_user.added_fliers + current_user.created_fliers)
   

  end

  if session[:organization_id] #if this is an organization, load all fliers
    @organization = current_user
    @fliers_for_org_liveboard = current_user.fliers
    @fliers_not_to_add = current_user.added_fliers + current_user.created_fliers
    @fliers_for_adding = @fliers_for_org_liveboard - @fliers_not_to_add
  end

end
end

app/helpers/liveboard_helper.rb
module LiveboardHelper
end

app/views/liveboard/_org_liveboard.html.erb
   <% @fliers_for_org_liveboard.each do |flier| %>

              <div class="fliers shadow">
              <%= image_tag flier.image.url(:thumb), class: "flimg" %>
              <%= link_to  flier.title, show_flier_path(:id => flier.id), class: "fltit" %>


                <% if @fliers_for_adding.include?(flier) %>
                  <%= button_to 'Add to my Billboard', org_add_flier_path(:flier_id => flier.id), class: "btn fladd" %>
                <% else %>

                <%end%>
          </div>
           <% end%>

app/views/liveboard/_user_liveboard.html.erb
 <% @fliers_for_liveboard.each do |myflier| %>

              <div class="fliers shadow">
              <%= image_tag myflier.flier.image.url(:thumb), class: "flimg" %>
              <%= link_to  myflier.flier.title, show_flier_path(:id => myflier.flier_id), class: "fltit" %>
              <%= myflier.myscore  %>

                <% if @fliers_for_adding.include?(myflier.flier) %>
                  <%= button_to 'Add to MyBoard', myboard_add_flier_path(:flier_id => myflier.flier_id), class: "btn fladd" %>
                <% else %>
                  <p> Already added </p>
                <%end%>
          </div>
            <%end%>

app/views/liveboard/index.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/header' %>
  </head>
  <body>

    <div class="container">

      <br/><br/>
 

        <h1> What's hap'nin, right now. </h1>
          <% if session[:user_id] %>
            <%= render 'user_liveboard' %>
           <%end%>
          <% if session[:organization_id] %>
            <%= render 'org_liveboard' %>
           <% end%>
    
         

        <br/><br/><br/><br/><br/><br/><br/>

      <%= render 'layouts/footer' %>

    </div>
  </body>
</html>