config/routes.rb
Lbdevelopmentv03::Application.routes.draw do

  get "guestlist/add"

  get "guestlist/remove"

  get "billboard/index"

  get "organization_fliers/add"

  get "organization_fliers/delete"

  resources :organizations

  get "realtime/subscription"

  get "realtime/verify"

  get "realtime/change"

  get "error_pages/not_friends"

  get "error_pages/friend_not_found"

  get "error_pages/not_your_flier"

  get "friends/display"

  get "channels/index"

  get "myboard/index"

  get "fliers/index"

  get "fliers/show"

  get "fliers/new"
  post "fliers/edit"

  get "fliers/edit"

  get "fliers/update"

  post "fliers/destroy"

  post "fliers/create"

  get "myfliers/invite"

  post "myfliers/send_invite"
  resources :users
  resources :fliers
  

  get "liveboard/index"

  get "users/create"

  get "users/update"

  get "users/show"

  get "users/destroy"

  get "pages/welcome"

  get "pages/contact"

  get "pages/about"

  get "pages/press"

  post "facebook_update/create"

  match 'login', to: 'auth/facebook'
  match 'logout', to: 'sessions#destroy'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: 'pages#welcome'
  match 'liveboard', to: 'liveboard#index', as: 'liveboard'
  match 'community_select', to: 'users#community_select'
  match 'myboard', to: 'myboard#index'
  match 'liveboard', to: 'liveboard#index'
  match 'myboard_add_flier', to: 'Myfliers#add'
  match 'myboard_delete_flier', to: 'Myfliers#delete'
  match 'contact', to: 'pages#contact'
  match 'help', to: 'pages#help'
  match 'about', to: 'pages#about'
  match 'facebook_update', to: 'facebook_updates#create', as: 'facebookupdates'
  

  match 'sessions_org_create', to: 'sessions#org_create'
  match 'sessions_redirect', to: 'sessions#registration_redirect'
  match 'org_logout', to: 'sessions#org_destroy'
  match 'create_organization', to: 'organizations#register'

  match 'channels/arts', to: "channels#index", :channel_id => "1"
  match 'channels/food', to: "channels#index", :channel_id => "2"
  match 'channels/lecture', to: "channels#index", :channel_id => "3"
  match 'channels/local', to: "channels#index", :channel_id => "4"
  match 'channels/nightlife', to: "channels#index", :channel_id => "5"
  match 'channels/sports', to: "channels#index", :channel_id => "6"

  match 'friends/:id', to: "friends#display"

  match 'not_friends', to: "error_pages#not_friends"
  match 'user_not_found', to: "error_pages#friend_not_found"
  match 'cant_view_flier', to: "error_pages#cant_view_flier"

  match 'create_flier', to: 'fliers#new'
  match 'show_flier', to: 'fliers#show'
  match 'invite', to: 'myfliers#invite'
  match 'edit_flier', to: 'fliers#edit'
  
  match 'org_add_flier', to: 'organization_fliers#add'
  match 'org_delete_flier', to: 'organization_fliers#delete'
  

  root :to => 'pages#welcome'

 
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :name, :community_id, :email, :image, :password, :password_confirmation

  has_secure_password
  validates_uniqueness_of :email
  validates :email, :presence => {:message => 'You must enter an email for your organization.'}
  validates :community_id, :presence => {:message => 'Please select a community for your organizatoin'}
  validates :name, :presence => { :message => 'Your organization needs a name.'}
  validates :image, :presence => { :message => 'Your organization needs an image.'}
  validates :password, :presence => { :message => 'Please enter a password.'}
  validates :password_confirmation, :presence => {:message => 'Please confirm your password.'}

  has_many :OrganizationFliers

  has_many :fliers, :through => :OrganizationFliers,
           :order => :added_count

  has_many :added_fliers, :through => :OrganizationFliers,
           :class_name =>"Flier",
           :source =>:flier,
           :conditions => ['attending_status=?', '1']

  has_many :created_fliers, :through => :OrganizationFliers,
           :class_name =>"Flier",
           :source =>:flier,
           :conditions => ['attending_status=?', '9']

  has_attached_file :image, :styles => { :thumb => "200 x 200", :large => "400 x 400"},
                             :quality => { :thumb => "-quality 80", :large => '-quality 80'}

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  skip_before_filter :logged_in_check, :has_community?
  def login
  
  end

  def create
    @organization = Organization.new(params[:organization])
      if @organization.save!
        redirect_to sessions_redirect_path, :flash => { :email => @organization.email }
      end
    
    
  end

  def register
    @organization = Organization.new
    @email = params[:email]
  end

  def update
    @organization = Organization.find(current_user.id)
    if @organization.update_attributes!(params[:organization])
      redirect_to liveboard_path, notice: "Your community has been added."
    end
  end


end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_login.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= form_tag sessions_org_create_path do %>
<%= label_tag :email %>
<%= text_field_tag :email %>
<%= label_tag :password %>
<%=  password_field_tag :password %>
<br/>
<%= submit_tag "Log-in or Register", :controller => 'Sessions', :action => 'org_create', class: "btn"  %>
<% end %>

app/views/organizations/register.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/header' %>
  </head>
  <body>

<p> We could not find an organization with that e-mail address.  You can create a new
organization by filling out this form.</p>


<%= form_for @organization, :html => {:multipart => true}, :validate => true do |f| %>
<%= f.label :email %>
<%= f.text_field  :email, :value => @email  %>
<%= f.label :community_id, 'Select Community:' %>
<%= f.select :community_id, options = {'Community' => '',
                                       'Amherst College' => '1',
                                       'University of Rochester' => '2',
                                       'Macalester College' => '3'}, class: "comsel" %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<%= f.label :image %>
<%= f.file_field :image %>

<br/>
<%= f.submit "Register", :controller => 'Organizations', :action => 'create', class: "btn" %>
<% end %>
  </body>
</html>