config/routes.rb
Lbdevelopmentv03::Application.routes.draw do

  get "guestlist/add"

  get "guestlist/remove"

  get "billboard/index"

  get "organization_fliers/add"

  get "organization_fliers/delete"

  resources :organizations

  get "realtime/subscription"

  get "realtime/verify"

  get "realtime/change"

  get "error_pages/not_friends"

  get "error_pages/friend_not_found"

  get "error_pages/not_your_flier"

  get "friends/display"

  get "channels/index"

  get "myboard/index"

  get "fliers/index"

  get "fliers/show"

  get "fliers/new"
  post "fliers/edit"

  get "fliers/edit"

  get "fliers/update"

  post "fliers/destroy"

  post "fliers/create"

  get "myfliers/invite"

  post "myfliers/send_invite"
  resources :users
  resources :fliers
  

  get "liveboard/index"

  get "users/create"

  get "users/update"

  get "users/show"

  get "users/destroy"

  get "pages/welcome"

  get "pages/contact"

  get "pages/about"

  get "pages/press"

  post "facebook_update/create"

  match 'login', to: 'auth/facebook'
  match 'logout', to: 'sessions#destroy'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: 'pages#welcome'
  match 'liveboard', to: 'liveboard#index', as: 'liveboard'
  match 'community_select', to: 'users#community_select'
  match 'myboard', to: 'myboard#index'
  match 'liveboard', to: 'liveboard#index'
  match 'myboard_add_flier', to: 'Myfliers#add'
  match 'myboard_delete_flier', to: 'Myfliers#delete'
  match 'contact', to: 'pages#contact'
  match 'help', to: 'pages#help'
  match 'about', to: 'pages#about'
  match 'facebook_update', to: 'facebook_updates#create', as: 'facebookupdates'
  

  match 'sessions_org_create', to: 'sessions#org_create'
  match 'sessions_redirect', to: 'sessions#registration_redirect'
  match 'org_logout', to: 'sessions#org_destroy'
  match 'create_organization', to: 'organizations#register'

  match 'channels/arts', to: "channels#index", :channel_id => "1"
  match 'channels/food', to: "channels#index", :channel_id => "2"
  match 'channels/lecture', to: "channels#index", :channel_id => "3"
  match 'channels/local', to: "channels#index", :channel_id => "4"
  match 'channels/nightlife', to: "channels#index", :channel_id => "5"
  match 'channels/sports', to: "channels#index", :channel_id => "6"

  match 'friends/:id', to: "friends#display"

  match 'not_friends', to: "error_pages#not_friends"
  match 'user_not_found', to: "error_pages#friend_not_found"
  match 'cant_view_flier', to: "error_pages#cant_view_flier"

  match 'create_flier', to: 'fliers#new'
  match 'show_flier', to: 'fliers#show'
  match 'invite', to: 'myfliers#invite'
  match 'edit_flier', to: 'fliers#edit'
  
  match 'org_add_flier', to: 'organization_fliers#add'
  match 'org_delete_flier', to: 'organization_fliers#delete'
  

  root :to => 'pages#welcome'

 
end

app/controllers/myboard_controller.rb
class MyboardController < ApplicationController
  def index
    @channels = Channel.all
    if session[:user_id]
      @invitations = current_user.invitations
      @created_fliers = current_user.created_fliers
      @added_fliers = current_user.added_fliers
      @flier_channels = []
      
      
    

    if session[:organization_id]
      @added_fliers = OrganizationFlier.find_all_by_organization_id_and_attending_status(current_user.id, '1')
      @created_fliers = OrganizationFlier.find_all_by_organization_id_and_attending_status(current_user.id, '9')
    end
  end
  end
end

app/helpers/myboard_helper.rb
module MyboardHelper
end

app/views/myboard/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/header' %>
  </head>
  <% if session[:user_id] %>
  <body>

  <div class="container">

        <br/><br/><br></br><br/><br/>

    <h1>My Board</h1>
    <h3>Added Fliers</h3>
    <% if current_user.added_fliers.empty? %>
        Nothing to see here yet.  Try checking out one of the channels.
    <%end%>
      <%unless current_user.added_academic_fliers.empty?%>
      <h3> Academic Fliers:</h3><br/>
          <% current_user.added_academic_fliers.each do |flier| %>
              <%= flier.image.url(:thumb) %>
              <%= flier.title %>
           <% end %>
       <%end%>

       <%unless current_user.added_arts_fliers.empty?%>
        <h3> Arts Fliers: </h3><br/>
          <% current_user.added_arts_fliers.each do |flier| %>
              <%= flier.image.url(:thumb) %>
              <%= flier.title %>
           <% end %>
       <%end%>

       <%unless current_user.added_nightlife_fliers.empty?%>
          <h3> Nightlife Fliers: </h3><br/>
          <% current_user.added_nightlife_fliers.each do |flier| %>
              <%= flier.image.url(:thumb) %>
              <%= flier.title %>
           <% end %>
       <%end%>

       <%unless current_user.added_sports_fliers.empty?%>
          <h3> Sports Fliers: </h3><br/>
          <% current_user.added_academic_fliers.each do |flier| %>
              <%= flier.image.url(:thumb) %>
              <%= flier.title %>
           <% end %>
       <%end%>


          <br/><br/>
          <h3>Created Fliers </h3>
        <% unless @created_fliers.empty? %>
          <% @created_fliers.each do |flier| %>
            <br/>
            <% @image =  image_tag flier.image.url(:thumb) %>
            <%= link_to @image, show_flier_path(:id => flier.id) %>
            <br/>
            <%= flier.title %><br/>
           
            <%= button_to 'Edit flier', :controller => "fliers", :action => "edit", :flier_id => flier.id %>
            <%= button_to 'Invite friends', invite_path(:flier_id => flier.id) %>
            <%= button_to 'Delete this flier', {:controller => "fliers",
                                               :action => "destroy",
                                               :flier_id => flier.id},
                                               :confirm => 'Are you sure?'%>
         
          <% end %>

        <% else %>
          No fliers here yet.  Try creating one.
          <br/><br/>
        <%end%>



        <% unless @invitations.empty? %>
        <p>Invitations:
          <% @invitations.each do |flier| %>
            <br/>
            <%= image_tag flier.image.url(:thumb) %>
            <br/>
            <%= flier.title %><br/>
            <%= button_to 'Add to My Board', myboard_add_flier_path(:flier_id =>flier.id) %>
          <% end %>
         <% end %>

        </p>


    <%=  render 'layouts/friends' %>
    <%= render 'layouts/footer' %>

  </div>

</body>
<%end%>
<% if session[:organization_id] %>


<%end%>
</html>